### PR TITLE
Storm drain modifications

### PR DESCRIPTION
**Pull request by rpachaly**

### CODE REVIEW

**Review by FLO-2DJJ — APPROVED** [review]

**Review by FLO-2DJJ — APPROVED** [review]

**Comment by FLO-2DJJ** [comment]
I reviewed the code and tested the plugin with four different projects: two old and two newly converted. Everything appears to be correct. The pull request has no conflicts with the master branch.

In my opinion, the pull request can be merged.

**Review by FLO-2DJJ — CHANGES_REQUESTED** [review]
Sorry @rpachaly, I just realized that in this pull request important changes were made to the code of method _auto_assign_link_nodes_ that modify my original functionality. Could you please restore it to the original one?

**Comment by rpachaly** [comment]
Ohh, I see... This is a merging problem. Let me fix it.

**Comment by rpachaly** [comment]
@FLO-2DJJ It was two functions that had merging problems, the auto_assign_link_nodes  and auto-assign. I rolled back both of them. Can you check if everything looks ok now?

**Review by FLO-2DJJ — APPROVED** [review]
Code reviewed and tested. Everything appears to be correct now. The pull request has no conflicts with the master branch.

In my opinion, the pull request can be merged.

@FLO-2DKaren, could you please give the final approval and merge it?

**Pull request merged**
