### PR TITLE
Path error rating table

### PR DESCRIPTION
**Pull request by rpachaly**

### CODE REVIEW

**Comment by FLO-2DJJ** [comment]
Hi @rpachaly, I see that this pull request has changes to the 'storm_drain_editor_widget.py' module. I've also been working on that module (and still working on it) in pull request #1179 (Storm Drain add storage units issue #1048). There have been 37 commits in total, changing, adding, or deleting lines in 31 files. Some of the commits affect storm_drain_editor_widget.py or relate it to other files.

There may be unexpected conflicts between the two pull requests when merged into master. 

Could you @rpachaly or @FLO-2DKaren wait until I finish issue #1048 and its pull request #1179 before merging this #1188 pull request?

**Comment by rpachaly** [comment]
Hi JJ, 

I basically added a line to fix the load a Rating Table error and changed the lastSWMMDir to lastGdsDir when exporting the SWMM file.

This pull request seems like a lot of stuff but it isn't. I had to remove a try/except to catch the bug and then I added back the try/expect. That's why it looks like I changed a lot of stuff. I don't think this is going to cause merging problems. And if that happens, it will be easy to fix the conflicts. But for me it is totally fine to wait :)

**Comment by FLO-2DJJ** [comment]
Hi Robson, 
OK. Now I see that the two-columns view (one pink and the other green) of the file that was modified in the two commits were excessively overextended for the changes made. That's how the changes are sometimes shown in GitHub.
No problem then. 
Thanks.

**Review by FLO-2DKaren — APPROVED** [review]
I tested import export, import inp and export inp, import rating tables. No problems.  I will merge this one if I don't get any conflicts.

**Pull request merged**
