### PR TITLE
Sd control

### PR DESCRIPTION
**Pull request by FLO-2DKaren**

### CODE REVIEW

**Comment by FLO-2DKaren** [comment]
@rpachaly 

Hi Robson,  I forgot about this branch.  Is it ready for testing?  Can I merge it?

**Comment by rpachaly** [comment]
Hi Karen,

My testing did not turn out well. I still need some time to have it fixed. 

However, it would be good if you want to do some testing. But it is not ready for merging.

**Comment by FLO-2DKaren** [comment]
OK I will test it today.

**Comment by rpachaly** [comment]
Hold on a bit, I'm finishing up my testing here.

**Comment by FLO-2DKaren** [comment]
I'm building a blank model to test this on.  I'll start with a storm drain import.

**Pull request merged**
