### PR TITLE
Fixed cursor

### PR DESCRIPTION
**Pull request by rpachaly**

### CODE REVIEW

**Comment by rpachaly** [comment]
@FLO-2DJJ Can you double check if the SD files are not affected by this pull request? If they are ok, please merge it.

**Comment by FLO-2DJJ** [comment]
Hi @rpachaly, I will double-check the SD files.

Initially, before your rollback, I was somewhat concerned that this pull request had modified several SD modules. These modules had been previously modified by me for the same purpose mentioned in issue #1249. I assume that with the rollback, the files were restored.

I will review this pull request as it is now.

**Comment by rpachaly** [comment]
Thanks! I hope this rollback works fine and we'll be able to finally fix the cursors with this pull request. 

This pull request must change only flo2d.py, flo2dgeopackage.py, and grid_tools_widget.py.

**Review by FLO-2DJJ — APPROVED** [review]
I thinks the changes are correct.
However, some of the changes to the mouse pointers precede a warning, error, or info message dialog which would be nice to be pointed to with an arrow. Will **restoreOverrideCursor** do that? We'll tested after it is merged to force the messages.
You can merge it, please.

**Comment by rpachaly** [comment]
Yes, we should **never** set the cursor to the Arrow Cursor (QApplication.setOverrideCursor(Qt.ArrowCursor)). We need to always use the QApplication.setOverrideCursor(Qt.WaitCursor) followed by a QApplication.restoreOverrideCursor().

From https://doc.qt.io/qt-6/qguiapplication.html#setOverrideCursor:

_Every setOverrideCursor() must eventually be followed by a corresponding [restoreOverrideCursor](https://doc.qt.io/qt-6/qguiapplication.html#restoreOverrideCursor)(), otherwise the stack will never be emptied._

If you set the arrow cursor, the cursor will **always** be the arrow cursor. If you try to expand a window, it will still be the arrow cursor. If you try to pan the map, it will still be the arrow cursor. That why wee need to always use the wait followed by the restore.

**Comment by FLO-2DJJ** [comment]
...and...
  *   finally*:
It is not that we should *never *set the cursor to an Arrow Cursor. Instead
we should *always *use the pair setOverrideCursor ... restoreOverrideCursor
.

For messages, I now apply the rule of thumb (using an arrow to replace
hourglass, pencil, zoom, or whatever the previous pointer was):

        QApplication.setOverrideCursor(Qt.ArrowCursor)

        *# Display a message dialog*

        # Restore the original cursor
        QApplication.restoreOverrideCursor()

However, as I mentioned earlier, within the plugin, some of the changes to
mouse pointers occur before a warning, error, or info message dialog.
During the message dialog, it would be helpful to use an arrow instead of
an hourglass, pencil, zoom, or whatever the previous mouse pointer was. We
need to review those adjustments.

Juan Jose Rodriguez
FLO-2D Software
www.flo-2d.com
***@***.***

**Comment by rpachaly** [comment]
I particularly don't like this approach. Let me explain why I don't like it.


```
 QApplication.setOverrideCursor(Qt.WaitCursor) -> Set the wait cursor prior running a code. 

 some code here

 QApplication.setOverrideCursor(Qt.ArrowCursor) -> Set the arrow cursor over the wait cursor.

 Display a message dialog

QApplication.restoreOverrideCursor() -> Restore the previous cursor, in this case the wait cursor and not the original cursor. 

```

In order to work properly, you need to call the QApplication.restoreOverrideCursor() twice. According to the QGuiApplication documentation:

_If [setOverrideCursor](https://doc.qt.io/qt-5/qguiapplication.html#setOverrideCursor)() has been called twice, calling restoreOverrideCursor() will activate the first cursor set. Calling this function a second time restores the original widgets' cursors._

 
Don't you think is simpler to restore the cursor before showing the message? This way, we reduce one line of code and avoid the potential error of setting one cursor over other. 

```
 QApplication.setOverrideCursor(Qt.WaitCursor) -> Set the wait cursor prior running a code. 

 some code here

 QApplication.restoreOverrideCursor()  -> Restore the previous cursor, in this case the original cursor.

 Display a message dialog
```

All this being said, if your code works, it's all good to me! The most important thing is to not set a wrong cursor for the user. :)

**Comment by FLO-2DJJ** [comment]
Hi Robson,

I apologize for persisting with this discussion about pointer management in
the Python plugin. I understand your perspective, but I still believe they
don’t function in the way you described. Let me explain further:

This is Copilot's response to the question (sorry, but sometimes I find AI
helpful):

When you execute QApplication.setOverrideCursor(Qt.ArrowCursor) in your
Python code, it sets the cursor to the *arrow cursor* (which is the default
cursor). Consequently, when users hover over your application’s widgets or
interface elements, the mouse pointer will appear as an arrow.

However, if you subsequently call QApplication.restoreOverrideCursor(), it
reverts the cursor to its original state. In this scenario, the original
cursor will be whatever was set before you applied the override. If no
other cursor was explicitly set, it will revert to the system’s default
cursor.

I genuinely want to understand the correct approach, as I may have been
handling this incorrectly.

Juan Jose Rodriguez
FLO-2D Software
www.flo-2d.com
***@***.***

**Pull request merged**
