### PR TITLE
1334 allow all types in lists in select components from shapefile

### PR DESCRIPTION
**Pull request by FLO-2DJJ**
- [x] _Inlet type_ for Inlets/Junctions is selected for both numeric and string types.
- [x] Smart search works for all drop down lists.

### CODE REVIEW

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren, please check this pull request. It corrects the issues from your video in #1334.

**Comment by FLO-2DKaren** [comment]
I'm going to test this now.

**Comment by FLO-2DKaren** [comment]
Tested and no errors.  All seems ok.

**Review by FLO-2DKaren — APPROVED** [review]
Tested and approved

**Pull request merged**
