### PR TITLE
Add storage units to auto assign link nodes

### PR DESCRIPTION
**Pull request by FLO-2DKaren**

### CODE REVIEW

**Comment by FLO-2DJJ** [comment]
Sorry @FLO-2DKaren, Did I make pull a request for this unfinished branch? Sorry If I did. 
But there is no problem to have merged it. There was no conflict with the master. 
Do not delete the branch, I'm still working on it. I'll make a new pull request later when I finish it.

**Comment by FLO-2DKaren** [comment]
Hi JJ,

I'm trying to do documentation and it's really hard to do this with 6 different branches.  I can't keep track of which branch I'm on and I go to document a tool and it's is missing  because the branch is super old.

I've been traveling so I'm working on a laptop and my main computer.  Hopefully I have everything back on track.

I wanted to try and get all of the code on the same page but I didn't trust the process so I gave up and merged it locally on my computer

I made the pull request but your branch should be ok.  Push it again if I deleted it.  Shouldn't hurt anything.

**Comment by FLO-2DJJ** [comment]
OK @FLO-2DKaren, 
( @FLO-2DNoemi, @rpachaly )

I understand. It is not bad practice to maintain a remote branch while working on the same local branch. The remote branch serves as both a backup and a means of communication with other collaborators, if necessary, during the branch’s development.

The pull request of the remote branch is done when the developer believes it is ready to be merged into the main master branch. At that point, the pull request can be reviewed by others to determine if it truly meets the criteria for approval and merging. 

After thorough revision, approval, and successful merging, the remote branch can be safely deleted. While I strive to follow these best practices, unfortunately, mistakes do happen occasionally.

For documentation purposes, this is the new look of the Storm Drain Editor widget (after deleting the combo box "Auto-assign link nodes' and replacing it with a push button):

image

You can run the remote branch 'add_storage_units_to_auto-assign_link_nodes' https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/tree/add_storage_units_to_auto-assign_link_nodes to see the current (unfinished) Storm Drain widget user interface.

**Comment by FLO-2DKaren** [comment]
Normally I'm happy to swap out branches.  But the current branches are so divergent that I'm having a hard time testing them.

I have some success merging code into my local master but I'm still missing big pieces of the master when I do that.  I hope next week to get our branches better aligned with the finished master.

**Pull request merged**
