### PR TITLE
SWMM.INP [TIMESERIES] group: write time series file name without path

### PR DESCRIPTION
**Pull request by FLO-2DJJ**
@FLO-2DKaren and @FLO-2DNoemi 
Please check that issue #918 is solved. There are 3 sub-issues here:
1. In [TIMESERIES] group of SWMM.INP: time series file name is now written without path.
2. Start and End dates and time can now be edited in dialog before exporting SWMM,INP file.
3. A warning is given if time series dates and times are not within Start and End dates and time in above dialog.

### CODE REVIEW

**Comment by FLO-2DKaren** [comment]
OK I can review it today.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ @FLO-2DNoemi 

The problem with this method.  If the end user doesn't save the timeseries file into the Export folder, the engine won't run.
You get a mysterious swmm error code and a crash report that is hard to understand.
That might not be intuitive.

I asked for a specific correction.  
Make the FilePath equal to the location of the timeseries file.   
If you want, we can copy the table into the geopackage and write the file at the same time as the inp export.
I believe that will solve this issue.

**Comment by FLO-2DKaren** [comment]
I am now testing the start time and end time and error messages

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
Before I merge this, I would like you to make this window collapsible.
image

**Comment by FLO-2DJJ** [comment]
Hi Karen,

Sorry for the misunderstanding about the time series path in SWMM.INP.
Now I corrected it following your instructions:

"Make the FilePath equal to the location of the timeseries file".

The pull request for #932 has the correction.

Juan Jose Rodriguez
FLO-2D Software
www.flo-2d.com
***@***.***

**Comment by FLO-2DJJ** [comment]
Hi Karen,

Why would you like to make this dialog collapsible?


Juan Jose Rodriguez
FLO-2D Software
www.flo-2d.com
***@***.***

**Review by FLO-2DKaren — APPROVED** [review]
Downloaded and tested.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 

Hi JJ, 
Can we have a meeting?  I'd like to discuss the control variables.  I've worked on the collapsible menu for them in order for us to understand how to do it better in the future.  I have something to show you.

**Comment by FLO-2DJJ** [comment]
OK Karen, let's have a meeting.
Can you this weekend? I can any day after your 11 am.

Juan Jose Rodriguez
FLO-2D Software
www.flo-2d.com
***@***.***

**Comment by FLO-2DNoemi** [comment]
We should allow 2 different ways to write this filename to the INP file,
with or without the path.  I think this is how EPA SWMM does it, and the
reasons are the following:

If you have the file in a different directory than your project folder, you
should be able to add the path to the INP file .

If you have the file inside your project folder, this is how FLO-2D data
files typically work, you do not need the path, you should be able to copy
the project folder from one computer to another computer without need to
update the path.

**Comment by FLO-2DKaren** [comment]
Let's focus on more important things.  It is working now and that is what
is important.

**Pull request merged**
