### PR TITLE
Outrc v3

### PR DESCRIPTION
**Pull request by rpachaly**

### CODE REVIEW

**Comment by FLO-2DKaren** [comment]
Hi Robson,

I was able to run this on self help and it took a few hours.  I didn't export it though because I was just testing to see if it processes.  I wasn't testing the output.

**Comment by FLO-2DKaren** [comment]
@rpachaly 
I don't want this to get too old because of conflicts.  But I'll leave that up to you.  Do you want to remove the processing button and then merge it?

**Comment by rpachaly** [comment]
Yes, I'll do it. Just give me 5 minutes.

**Comment by rpachaly** [comment]
@FLO-2DKaren all good for merging

**Pull request merged**
