### PR TITLE
Fix #844

### LINKED ISSUE #844: Green Ampt Error
@vcloarec 

Hi Vincent,
I got this error when trying to calculate green ampt.  Can you please fix it for me.  
image

Here's the project
https://flo-2d.sharefile.com/d-s63af289cc1614faf9eb63413ca54f738

### PR DESCRIPTION
**Pull request by vcloarec**
Fixes #844.
Also change a bit the calculation of RTIMP. Indeed, the modification introduced by #834 contains an error related to the intersection between soil layer and land use layer to calculate the max RTIMP.
This new approach can slow down the calculation but is necessary to have a good calculation of the intersection between soil and land use. The speed of the calculation is linked a lot to the complexity of soil and land use layers.

### CODE REVIEW

**Comment by FLO-2DKaren** [comment]
@vcloarec 
This will not work.  It is too slow.   It was processing my Large Test Project in a relatively good time before but now it's progress is 3 hours on and not even close to finishing.  We'll have to come up with something else.

image

**Comment by vcloarec** [comment]
@FLO-2DKaren , indeed your project is huge... I understand that the process is long, and we have to change the approach to allow this type of project.

The approach that I have implemented have the assumption that it is possible to have some part of the domain that is cover only by soil layer OR by land use layer. In that case, the RTIMP value considered is simply the one of the polygon that exists.
This assumption leads to a more time consuming logic.

I am testing a new approach.

I am wondering if we can consider that if one of the soil layer OR the land use layer do not cover an area, in this area we haven't a RTIMP value from any layers (soil or land use) at all. This is for reduce the process time about 50%.

**Comment by vcloarec** [comment]
@karen, you can try this new version

**Comment by FLO-2DKaren** [comment]
OK testing now.

**Pull request merged**
