### PR TITLE
Add channel baseflow to chan dat

### PR DESCRIPTION
**Pull request by FLO-2DJJ**
Lines B added at end of CHAN.DAT

### CODE REVIEW

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren, @FLO-2DNoemi
This pull request writes the B lines at the end of CHAN.DAT

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren,

Do not merge it yet. Importing CHAN.DAT with B lines at the end of the file is not finished.

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren,

- [ ] Importing CHAN.DAT with B lines at end of file finished. 

You can now test this pull request and merge it to master if satisfied.

**Review by FLO-2DKaren — APPROVED** [review]

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ I'm going to merge this so I can test a single version.

**Pull request merged**
