### PR TITLE
Hdf5 import export

### PR DESCRIPTION
**Pull request by ldebek**
Core changes were made in `flo2d_parser.py`, `flo2dgeopackage.py` and `flo2d.py`. Rest of the changes are result of running code autoformating tools: `black` and `isort`, so those can be just ignored in terms of code review.

### CODE REVIEW

**Comment by FLO-2DKaren** [comment]
@ldebek 
Hi Lukasz,  I am now getting this error when I export GDS.  I didn't get the error when I export hdf.

image

Here is my QGIS version data.

QGIS version
3.28.5-Firenze
QGIS code revision
50adba36f2
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.3
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
flo2d
0.10.97
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

**Comment by FLO-2DKaren** [comment]
@ldebek 
Hi Lukasz,  I think there is another error when I import GDS that is related to this error of cont_toler.

**Comment by ldebek** [comment]
> @ldebek Hi Lukasz, I think there is another error when I import GDS that is related to this error of cont_toler.

Hi @FLO-2DKaren I couldn't reproduce this issue - import/export from/to GDS seems to work just fine for me. Please share an example model data with me, so I can test it. It would be also good if you could check if it works for you with code from the current master branch to make sure if bug was already there before or is it a regression.

**Comment by FLO-2DKaren** [comment]
@ldebek 

I may have corrupted my file because I've been messing around in version QGIS version 3.30.  I'll rebuild Lesson 1 and try it again.

**Comment by FLO-2DKaren** [comment]
@ldebek 
I think there is a bug.  My test works with the master plugin.

Rebuild the QGIS Profile.  Sometimes swapping between 3.28 and 3.30 causes profile conflicts.
Open 3.28 and rebuild Lesson 1
Export GDS files and get empty cont.dat file and error message shown above.
Reload Master Plugin and error is gone.

I did note that there are some conflicts with your plugin but I don't know if they are important or not.

**Comment by FLO-2DKaren** [comment]
@ldebek 
Just a note that my error happens when I export *.DAT files not when I export hdf5 files.

**Comment by FLO-2DKaren** [comment]
Method:
1. I load the plugin from the hdf5 branch.  I copy the files in flo2d into my plugin folder.  I delete the old files first.
2. Create geopackage lesson 1a.gpkg.  epsg 2223
3. Task Failed message appears.
image

4. Import cont.dat, toler.dat, topo.dat, mannings_n.dat.  **Import OK**
5. Run **Export GDS Files**.  Error appears.
image

6. CONT.DAT is empty and TOLER.DAT is not written.
image

[Lesson 1 Import Export Test.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/11211573/Lesson.1.Import.Export.Test.zip)

**Comment by ldebek** [comment]
@FLO-2DKaren I've pushed fix for export to GDS format. Issue should be fixed now.

**Comment by FLO-2DKaren** [comment]
@ldebek 
Testing now.

**Comment by FLO-2DKaren** [comment]
@ldebek 
Hi Lukasz

Next Failed Test

Method.
Create empty Geopackage.
Import *.hdf5 file
Export *.DAT files

image

**Comment by FLO-2DKaren** [comment]
@ldebek 
Lukasz,

I merged JJ's branch so you will have some conflicts to resolve when your merge is ready.

**Comment by ldebek** [comment]
> @ldebek Lukasz,
> 
> I merged JJ's branch so you will have some conflicts to resolve when your merge is ready.

@FLO-2DKaren TypeError which you reported should be fixed now. Changes from the master branch are resolved now as well.

**Review by FLO-2DKaren — APPROVED** [review]
Tests Performed
Load Lesson 1 Export *.DAT
Run flopro.exe
Run OK
Export *.hdf5
Import *.hdf5
Export *.DAT from hdf5 import.
Import *.DAT from hdf5 import.
Export *.DAT again and run FLOPRO.EXE
OK

**Pull request merged**
