### PR TITLE
SD add RT and Culvert

### PR DESCRIPTION
**Pull request by FLO-2DJJ**
- Can add a rating table or Culvert Eq.
- Can rename tables.
- Culvert Eq MULTBARRELS default = 1

### CODE REVIEW

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren, @FLO-2DNoemi 

- This plugin allows renaming of RT and Culvert eq.
- MULTBARRELS defaults to 1.
- Note that time ago the 'Rating Table or Culvert Eq.' list was disabled.
image
User can't choose one of them from the list. The association of RT/Culvert eq. to inlet is done importing file with the same name of inlet (was decided with @FLO-2DNoemi long time ago).

**Comment by FLO-2DNoemi** [comment]
I need to review the Rating table / culvert.

Using a file with the same name of the inlet for rating table / culvert
equation was decided long time ago and I think it is a simple way to
correlate the data with the inlet type 4.

The possibility to enter the culvert data manually for an inlet type 4 was
not completed in the past because it required additional time/effort  but
it is needed.

Noemi

**Comment by FLO-2DNoemi** [comment]
Sounds good, thanks!

**Comment by FLO-2DJJ** [comment]
> @FLO-2DNoemi I did a review on it and I found very minor things that need to be fixed. Don't do a review yet. Once JJ and I deal with the stuff I found, we'll let you test it.

Hi @FLO-2DKaren, what are the fixes I need to address in this pull request?

**Pull request closed without merging**
