### PR TITLE
Storm Drain add storage units issue #1048

### PR DESCRIPTION
**Pull request by FLO-2DJJ**
@FLO-2DNoemi, @FLO-2DKaren Please review this branch with the Storage Units functionality.
A brief introduction is described in this video: 

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/17e939fc-026b-4fd0-8fdb-6792f3eedaac

### CODE REVIEW

**Comment by FLO-2DKaren** [comment]
Hi JJ,

I need to test this before I merge it.  I will do that as soon as I can get some free time.

**Comment by FLO-2DJJ** [comment]
Hi @FLO-2DKaren, the code of this pull request now resolves these sub-issues:

- No dates in times series must be allowed (in [TIMESERIES] group.
- Storage Unit not finding its conduit.
- Conduit has no inlet defined.
- Conduit has no outlet defined.

Some other sub-issues in #1048 still pending.

**Comment by FLO-2DKaren** [comment]
@rpachaly Hi Robson,
I can't test this because it won't autoport a geopackage. I have a Lesson 1 that I want to test it with but I can't load it.  Can you check that out?

**Comment by rpachaly** [comment]
> @rpachaly Hi Robson, I can't test this because it won't autoport a geopackage. I have a Lesson 1 that I want to test it with but I can't load it. Can you check that out?

Can you upload the gpkg? I tried it here and it autoported without any issues

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren, @FLO-2DNoemi, @rpachaly
This pull request is ready to be reviewed.
It includes all the functionality explained in the video above and all the sub-issues detailed in https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/1180.
Please look at it. If approved it can be merged into the current master.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ  I was hoping to review this today but someone needed my computer art the class.

**Review by FLO-2DKaren — APPROVED** [review]
@FLO-2DJJ 
JJ,  I'm going to merge this with the master so I can test it and the info tools at the same time.

**Pull request merged**
