### PR TITLE
new RTIMP calculation

### PR DESCRIPTION
**Pull request by vcloarec**
Related to #765

Introduces a new user layer : "Effective impervious areas".

@FLO-2DKaren , I don't have opinion about the symbology of this new layer. Any opinion ?
Other point, you want to regroup some layers, including this one. Do you have a name for this group ?
Waiting this information to finish this PR.

### CODE REVIEW

**Comment by FLO-2DKaren** [comment]
@vcloarec 

I don't have an opinion but if it's easy, start from Froude Areas and modify the color.

**Comment by vcloarec** [comment]
image

**Comment by FLO-2DKaren** [comment]
@vcloarec 
Sorry I missed your other question.  Yes, let's group those into Infiltration under the User Group.
I'll see if I can get a image with some other groups.

**Comment by vcloarec** [comment]
@FLO-2DKaren , after looking how to group some layers when creating the project, it seems more complicated than I thought, maybe we can deferred this to later?

**Comment by FLO-2DKaren** [comment]
@vcloarec 
Oh Good.  I thought it was me!!!  Yes let's defer this.  I'll add a note to the Groups issue too.

**Pull request merged**
