### PR TITLE
Sd outside grp

### PR DESCRIPTION
**Pull request by rpachaly**

### CODE REVIEW

**Review by FLO-2DJJ — DISMISSED** [review]

**Comment by FLO-2DJJ** [comment]
I tested the pull request with a shapefile layer outside the project group.

image

When the project is closed, the outside shapefile is moved to new group _External Layers_:

image

There is no problem with the dialog _Select components from shapefile layer_; it keeps the reference to the moved layer.

I suppose that's OK. I'm just mentioning it because in a previous plugin, all the shapefiles where moved to the _External Layers_, but in a subsequent plugin, they are keep inside _Storm Drain_.

But, again, I'm just checking that this pull request does what we want.

**Comment by rpachaly** [comment]
If the layer is **inside** the Storm Drain User Group, it will be saved there. If the layer is **outside** the Storm Drain User Group, it will be saved on the External Layers Group.

**Review by FLO-2DJJ — APPROVED** [review]

**Comment by FLO-2DJJ** [comment]
> If the layer is **inside** the Storm Drain User Group, it will be saved there. If the layer is **outside** the Storm Drain User Group, it will be saved on the External Layers Group.

Ok. That's fine. I was just checking. I'll give my approval.

**Comment by rpachaly** [comment]
JJ, I've added a commit to this pull request addressing https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/1331

It worked on my testing, but you are more familiar with the code. Can you test it?

Thanks!

**Comment by FLO-2DJJ** [comment]
> JJ, I've added a commit to this pull request addressing #1331
> 
> It worked on my testing, but you are more familiar with the code. Can you test it?
> 
> Thanks!

The pull request was merged. I'll test it in my local repo.

**Comment by FLO-2DJJ** [comment]
> JJ, I've added a commit to this pull request addressing #1331
> 
> It worked on my testing, but you are more familiar with the code. Can you test it?
> 
> Thanks!

Hi @rpachaly,

I tested the solution to #1331. It looks good. I saw internal code structure and logic, and ran several cases. It is fine.

Maybe, in the future, we could  check that the fields selected from the shapefiles are of the same type of the layer fields. For example, if the user selects a string to assign to a number, an error may immediately occur or cascade for a later error, like:

image

image

**Comment by FLO-2DJJ** [comment]
On second thoughts, I'm going to include an issue for my above comment: #1334

**Pull request merged**
