### PR TITLE
1327 swmmoutf issue

### PR DESCRIPTION
**Pull request by FLO-2DJJ**
Outfalls dialog: 

- When the 'Allow Discharge' checkbox is checked, the _Allow Discharge_ column is set to 1/0.
- On loading, the _Allow Discharge_ column is set to 1 or 0.
- Save the _Allow Discharge_ values to _outf_flo_ field of **swmmoutf** table (SD Outfalls layer).
- Saves/Loads SWMMOUTF.DAT according to edits described above.

### CODE REVIEW

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren, @FLO-2DNoemi,

Please review this pull request. The changes/fixes to see are described the first comment above.

At this moment, it can be merged into master without conflicts.

**Comment by FLO-2DKaren** [comment]
JJ,  It needs to be 0, 1 or 2 so the checkbox is not needed.  You can use a combo box or let the people edit it in the table.

**Comment by FLO-2DJJ** [comment]
Hi @FLO-2DKaren,

> JJ, It needs to be 0, 1 or 2 so the checkbox is not needed. You can use a combo box or let the people edit it in the table.

This is new. Could you please document it, to see the logic behind this change, and adapt it to the code.

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren,

Before this:

    SWMMOUTF AllowQ is no longer true false. It is now 0, 1, or 2

I had already changed the plugin to remove True/False and change it to 1/0 in all the code related to _Allow Discharge_. That was according to a previous video you sent to me. I did it in a code that was integrated to pull request https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1329

The fact that _Allow Discharge_ is now 0,1,2 is new. Could you please document it, so I can see the logic behind this change, and adapt it to the code.

Please, do not merge this pull request until the final range of _AllowQ_ is clarified.

**Review by FLO-2DKaren — APPROVED** [review]

**Comment by FLO-2DJJ** [comment]
This pull request was not finished yet:

> Please, do not merge this pull request until the final range of _AllowQ_ is clarified.

It's about to be finished, but needs a couple of additions.

**Comment by FLO-2DKaren** [comment]
I expected it to be finished yesterday so I can wrap up my documentation and testing.

**Comment by FLO-2DJJ** [comment]
> I expected it to be finished yesterday so I can wrap up my documentation and testing.

That's OK. I created a new branch to finish it #1335.

**Pull request merged**
