### PR TITLE
fix slow import gpkg (#840)

### PR DESCRIPTION
**Pull request by vcloarec**
WORK IN PROGRESS

Here, no more layer "infil_areas_green", so no more trigger for green ampt infiltration. 

I have to treat other infiltration type, but for green_ampt that seems to work, and it can be tested. In the meanwhile, I will look for other infiltration types.

However, in this configuration, when importing from gpkg with infiltration, values of green ampt infiltration are not imported. It comes from, when importing from gpkg, the importation is done simply by copying layer/tables to the new gpkg files. As "infil_areas_green" does not exist anymore in the destination, values are not copied.
In that case it is necessary to recalculate green ampt infiltration. 
If it is a problem (**please, tell me**), we need to add a logic for this particular case when importing: if there is a "infil_areas_green" layer with values in source gpkg, we have to copy them to "infil_cells_green" instead of trying to copy from the "infil_cells_green" table.

Other point: "infil_areas_green" layer is also used here: https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/blob/3fe84e9cc86f7e7920316d1775bc953fe5a7c887/flo2d/flo2d_tools/schema2user_tools.py#L322
This is the only place where the code remains to be adapted. Not sure, but this class seems to not be used anywhere, so maybe it is not necessary to change the logic here, only remove the reference of the layer, and the new logic could be implemented later if the class is used again. @FLO-2DJJ , any idea about the usefulness of this class?

### CODE REVIEW

**Comment by FLO-2DJJ** [comment]
Ok. Very  interesting. I'll if I see any conflicts. Firstly by searching,
but later today I need to pull the repository into mine, so it will show
any problems if any.
Thanks Vincent.

**Comment by FLO-2DKaren** [comment]
@vcloarec 

I did an import from old gpkg but the numbers didn't come in.  The test is to import an old gpkg into a new gpkg.  Do I need to do something different?

image

**Comment by FLO-2DKaren** [comment]
@vcloarec I just read your instructions more clearly. Let me see how hard it is to copy the data.

**Comment by vcloarec** [comment]
@FLO-2DKaren , yes when importing an old gpkg, values are not copied, as I said in my comment, but maybe not very clear due to my not so good English.
You need to recalculate the value. That's  why I asked if it is a problem. If it is a problem, we have to implement a logic to treat this particular case when importing a old gpkg.

**Comment by vcloarec** [comment]
> Let me see how hard it is to copy the data.

What do you mean: do you want to implement the copy of data in the plugin or see how it is hard to copy the data manually?

**Comment by FLO-2DKaren** [comment]
@vcloarec 

Sorry for the miscommunication.   I didn't read your instructions very carefully.  It's written just fine and I think I understand the process.  I will test it and get back to you with any issues.

**Comment by vcloarec** [comment]
In the last commit, modification is done also for other infiltration types.

**Comment by FLO-2DKaren** [comment]
@vcloarec 

OK I have an idea.  How about instead of recalculating infiltration, we can import it using the red import button.

image

Can you make it so that fills the table?  We'll need that to be working anyway.

**Comment by vcloarec** [comment]
> Can you make it so that fills the table? We'll need that to be working anyway.

I will look at

**Comment by vcloarec** [comment]
With the last commit, I think you can import only one GDS file.

**Comment by FLO-2DKaren** [comment]
OK I'll test it.

**Comment by FLO-2DKaren** [comment]
The other import worked OK but the export is now not working.

image

**Comment by FLO-2DKaren** [comment]
@vcloarec 

hi Vincent.  See the comment above and I  might have another error in the calculator.

image

**Comment by vcloarec** [comment]
For the first comment, maybe you infiltration table for SCS has the old structure? As structure of some tables have change, it necessary to create a new project and import from gpkg. Then, you can import infiltration values from INFIL.DAT.

For the second comment, have you some elements in the grid? It seems the associated vector layer can't return the number of feature.
In any case, there is an new commit that avoid this error.

**Comment by FLO-2DKaren** [comment]
@vcloarec 

OK Testing is back on.  Both errors are now passing.  I'll have to test GreenAmpt, SCS, and Horton.

Notes for @FLO-2DKaren 

Things to test

- [ ] Start from scratch calculate from external shapefile. all 3 types.
- [ ] Export data filies.
- [ ] Import geopackages with different infiltration types.
- [ ] Export after import.
- [ ] Import single files.
- [ ] Export after import

Spot check calculations.

- [ ] GreenAmpt
- [ ] GreenAmptSchema
- [ ] SCS
- [ ] SCSSchema
- [ ] Horton
- [ ] Horton Schema

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 

JJ,  this has a lot of changes.  Can you please make sure it's not going to overwrite or undo anything you posted this week?  It has 8 changed files.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
This branch will overwrite 8 files.  If you happened to also work on one of these files within the last 7 days, your work will be undone.  If you could simply look at the 8 files.  If you worked on one of these files, we need to be more careful when we merge this pull request.

**Comment by FLO-2DJJ** [comment]
Ok. Tomorrow I'll look carefully to the files to see if there is any
conflict.

**Comment by FLO-2DJJ** [comment]
I merged @Vincent Cloarec ***@***.***>'s pull
request and pulled the new master into my repository without problem. 👍

Juan Jose Rodriguez
FLO-2D Software
www.flo-2d.com
***@***.***

**Pull request merged**
