### PR TITLE
Call external C# program to execute FLOPRO.EXE

### PR DESCRIPTION
**Pull request by FLO-2DJJ**
@FLO-2DNoemi, @FLO-2DKaren Please test this plugin that calls FLOPRO.EXE from an external C# program. 
You need include this C# program and dependencies in the same folder of FLOPRO.EXE:

[FLOPROCore..zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/11721253/FLOPROCore.zip)

### CODE REVIEW

**Comment by FLO-2DJJ** [comment]
Please, replace the FLOPROCore.exe program with this one.
It is is smaller. It is the same C# program with different VS project and publish parameters. It is supposed to be self-contained.  Try it please.

[FLOPROCore.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/11743031/FLOPROCore.zip)

**Comment by FLO-2DNoemi** [comment]
It worked without any problem.

Karen, is working on your computers?

Noemi

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
I think I'm running .NET version 4.0 on this computer if that helps.  I don't want to update it since Tailings Dam Tool works fine.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
JJ, I extracted the Tailings Dam Tool.exe with 7zip and it says that Windows .NET 4 is the version
Can you set Windows .NET 4 for the FLO-2D Core.  I'm guessing your computer is Windows 11.

Tailings Dam Breach       	Microsoft    Copyright Â© Microsoft 2014
.NETFramework,Version=v4.8 TFrameworkDisplayName.NET Framework 4.8# PresentationBuildTasks4.0.0.0          T
ElementNameDelta_tT  TElementNameQQp  TElementNameQQpQPeak  TElementNameCvCvmax 
Hydrograph  A 3System.Resources.Tools.StronglyTypedResourceBuilder17.0.0.0  Y

**Comment by FLO-2DKaren** [comment]
@FLO-2DNoemi 
It didn't work on my new harddrive but the tailings dam tool runs just fine.   So I think JJ needs to try again.  If you view the messages in GitHub, you'll see my other comments.

**Comment by FLO-2DNoemi** [comment]
@Karen OBrien ***@***.***>  I saw your comment regarding the NET
framework.

@Juan Jose Rodriguez ***@***.***> Yesterday when we were reviewing the
properties of the tool, there was one property related to the NET version.
We can review this together if you need to.

**Comment by FLO-2DNoemi** [comment]
I see the problems Karen is reporting.
Our Tailings Dam is WPF (Windows Presentation Foundation UI framework)
using the NET 4.8 libraries. In VS you can see (in Project properties)
that the target NET framework can be selected from a list. It is set as NET
4.8.
But FLOPROCore is defined as WinForm UI. That can not be changed. That's
how I created it. It uses the NET 7 framework but it doesn't seem to be
able to set it to 4 or 4.8:
[image: imagen.png]

It runs for NET 6 also but not for NET 5.
It seems to me that we have 2 options here: install NET 6 or 7 in the
computer, which Karen doesn't like with good reasons, or create a new
FLOPROCore based on WPF as Tailings Dam is.
The second option is not that difficult really.

Or we can meet again today to review the whole situation.


Juan Jose Rodriguez
FLO-2D Software
www.flo-2d.com
***@***.***

**Comment by FLO-2DNoemi** [comment]
I don't think we need a meeting.  I like the second plan to use the wpf
like tailings dam tool.

**Comment by FLO-2DNoemi** [comment]
👍

**Comment by FLO-2DNoemi** [comment]
@Juan Jose Rodriguez ***@***.***> I agree with Karen, we should
implement option 2.

**Comment by FLO-2DJJ** [comment]
Let's try it again !
This pull request plugin calls an eternal C# program that in turn calls FLOPRO.EXE. It is written in C# with WPF and NET 4.8 (as the Tailing Dam program).
Please remove all previous FLOPROCore.* files (program and dependencies) from the folder where FLOPRO.EXE is.
And place this unique new RunFLO-2D.exe program in the model folder:
[RunFLO-2D.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/11769142/RunFLO-2D.zip)

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ @FLO-2DNoemi I can test it right now.

**Comment by FLO-2DKaren** [comment]
Haha I can't even open it.  Windows thinks it's a virus.  Let me see if I can find out why windows thinks it's a virus.

image

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ  
This is probably a simple compiler issue.  Can you make sure you are ticking all the right boxes?  It could be something as simple as a missing  name, author, description.   

I found these ideas online:
Have you provided an AssemblyInfo.cs 
Building the program in Release could also fix the problem.
Don't build it in Debug mode.

Can Visual Studio scan an exe and tell you why it's being flagged?  


If you can fix this, I think we'll have you compile our activator too.  That one is always flagged and blocked as a virus.  It is very annoying.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
Remember we are going to be calling this from the App directory not the LastFLOPRO location.  Please sort that out too.

**Pull request merged**
