### PR TITLE
Add load and save external files to outfall tidal dialog

### PR DESCRIPTION
**Pull request by FLO-2DJJ**
The Outfalls dialog for tidal curves has now a "Load File..." and a "Save File.." buttons:
imagen

@FLO-2DNoemi , @FLO-2DKaren     Please review it.

Next: I'm working at the moment on a "Paste" functionality,

### CODE REVIEW

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
I'm going to wait to test this for when the paste button is in.

**Comment by FLO-2DJJ** [comment]
Yes Karen, I also think that's the way to go.

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren, @FLO-2DNoemi:
Outfalls Tidal Curve Dialog: This pull request contains functionality to "Save", "Load", "Copy", and "Paste"

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
I'm testing this right now.

**Review by FLO-2DKaren — APPROVED** [review]

**Pull request merged**
